export default [
  { name: 'HUAWEI G8 4G', price: 350, id: 1, imgSrc: './assets/wish-item4.png' },
  { name: 'Apple iPhone 6S', price: 550, id: 2, imgSrc: './assets/wish-item2.png' },
  { name: 'HUAWEI G8 4G', price: 350, id: 3, imgSrc: './assets/wish-item4.png' },
  { name: 'SONY XPERIA Z5', price: 550, id: 4, imgSrc: './assets/wish-item5.png' },
  { name: 'Apple iPhone 6S', price: 550, id: 5, imgSrc: './assets/wish-item2.png' },
  { name: 'Galaxy Core Prime ', price: 399, id: 6, imgSrc: './assets/wish-item7.png' },
  { name: 'HUAWEI G8 4G', price: 350, id: 7, imgSrc: './assets/wish-item4.png' },
  { name: 'Galaxy Core Prime ', price: 399, id: 8, imgSrc: './assets/wish-item7.png' },
  { name: 'Huawei Mate S', price: 280, id: 9, imgSrc: './assets/wish-item1.png' },
  { name: 'Galaxy Core Prime ', price: 399, id: 10, imgSrc: './assets/wish-item7.png' },
  { name: 'Xiaomi Mi 4i', price: 350, id: 11, imgSrc: './assets/wish-item3.png' },
  { name: 'Xiaomi Mi 4i', price: 350, id: 12, imgSrc: './assets/wish-item3.png' },
  { name: 'Huawei Mate S', price: 280, id: 13, imgSrc: './assets/wish-item1.png' },
  { name: 'iPhone Rose Gold', price: 280, id: 14, imgSrc: './assets/wish-item2.png' },
  { name: 'iPhone Rose Gold', price: 280, id: 15, imgSrc: './assets/wish-item2.png' },
  { name: 'iPhone Rose Gold', price: 280, id: 16, imgSrc: './assets/wish-item2.png' },
  { name: 'HUAWEI G8 4G', price: 350, id: 17, imgSrc: './assets/wish-item6.png' },
  { name: 'SONY XPERIA Z5', price: 550, id: 18, imgSrc: './assets/wish-item5.png' },
  { name: 'Xiaomi Mi 4i', price: 350, id: 19, imgSrc: './assets/wish-item3.png' },
  { name: 'SONY XPERIA Z5', price: 550, id: 20, imgSrc: './assets/wish-item5.png' },
  { name: 'Huawei Mate S', price: 280, id: 21, imgSrc: './assets/wish-item1.png' },
  { name: 'HUAWEI G8 4G', price: 350, id: 22, imgSrc: './assets/wish-item6.png' },
  { name: 'HUAWEI G8 4G', price: 350, id: 23, imgSrc: './assets/wish-item6.png' },
  { name: 'Apple iPhone 6S', price: 550, id: 24, imgSrc: './assets/wish-item2.png' },
];
